<a href="https://colab.research.google.com/github/Dattatray685/python_notes_by_datta/blob/main/task_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆)
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 3. Create a null vector of size 10 (★☆☆)
(**hint**: np.zeros)

In [ ]:
a = np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)
(**hint**: size, itemsize)

In [ ]:
print(a.itemsize)

8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
(**hint**: np.info)

In [ ]:
import numpy as np
print(np.info)

<function info at 0x7f05affb5260>


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
(**hint**: array\[4\])

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
(**hint**: np.arange)

In [ ]:
#np.arange(start,stop,step)
a = np.arange(10,49,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
(**hint**: array\[::-1\])

In [ ]:
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
(**hint**: reshape)

In [ ]:
b = np.arange(0, 9).reshape(3, 3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
(**hint**: np.nonzero)

In [ ]:
c = np.array([1,2,0,0,4,0])
np.indices = np.nonzero(c)
print(c)

[1 2 0 0 4 0]


#### 11. Create a 3x3 identity matrix (★☆☆)
(**hint**: np.eye)

In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
(**hint**: np.random.random)

In [ ]:
a = np.random.randint((2,3,3))
print(a)

[0 0 1]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(**hint**: min, max)

In [ ]:
b = np.random.randint((10,10))
#print(b)
print(b.min())
print(b.max())

7
8


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
(**hint**: mean)

In [ ]:
b = np.random.randint((10,10))
print(b.mean())

2.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
(**hint**: array\[1:-1, 1:-1\])

In [ ]:

a = np.zeros((5,5))

a[0, :] = 1
a[-1, :] = 1
a[:, 0] = 1
a[:, -1] = 1

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
(**hint**: np.pad)

#### 17. What is the result of the following expression? (★☆☆)
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
(**hint**: np.diag)

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)
print(np.diag(a))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  7 13 19 25]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
(**hint**: array\[::2\])

In [ ]:
a = np.zeros((8,8))

a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(**hint**: np.unravel_index)

In [ ]:
d = np.unravel_index(99, (6,7,8))
print(d)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
(**hint**: np.tile)

#### 22. Normalize a 5x5 random matrix (★☆☆)
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5,5))
#print(a)
b = (a - a.min()) / (a.max() - a.min())
print(b)

[[0.68154365 0.44505092 0.         0.75428815 0.33594229]
 [0.8088425  0.7845113  0.49098594 0.89495291 0.23389303]
 [0.93541197 0.05388127 0.61872459 0.55975716 0.35663759]
 [0.31047023 0.3536865  0.4563462  0.86777096 1.        ]
 [0.65046446 0.26464992 0.30375567 0.57271257 0.83538651]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(**hint**: np.dtype)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b.dtype)

int64


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(**hint**: np.dot | @)

In [ ]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(np.dot(a,b))

[[1.13174473 1.08041354]
 [1.10025308 1.16008606]
 [0.98469079 0.69993353]
 [0.89281006 1.00211285]
 [1.14945795 1.14915153]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(**hint**: >, <=)

In [ ]:
a = np.array([1, 4, 6, 2, 8, 10, 3])
a[(a > 3) & (a <= 8)] *= -1
print(a)

[ 1 -4 -6  2 -8 10  3]


#### 26. What is the output of the following script? (★☆☆)
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_31139/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_31139/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_31139/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.array([-1.2,2.3,-2.0,1.3])
b = np.copysign(np.ceil(np.abs(a)),a)
print(b)

[-2.  3. -2.  2.]


#### 30. How to find common values between two arrays? (★☆☆)
(**hint**: np.intersect1d)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7,])
c = np.intersect1d(a,b)
print(c)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np
np.errstate(all = 'ignore')
print(np.array(0) / np.array(0))


nan


/tmp/ipykernel_2396/4098082357.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


#### 32. Is the following expressions true? (★☆☆)
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_2396/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1 ,"D")
tomorrow = today + np.timedelta64(1 ,"D")

print(today)
print(yesterday)
print(tomorrow)

2026-04-08
2026-04-07
2026-04-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:

dates = np.arange('2016-07', '2016-08', dtype="datetime64[D]")
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.array([1,2,3], dtype=float)
B = np.array([4,5,6], dtype=float)

np.add(A, B, out=B)        # B = A + B
np.divide(A, 2, out=A)     # A = A/2
np.negative(A, out=A)      # A = -A
np.multiply(B, A, out=A)   # A = (A+B)*(-A/2)

print(A)


[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.random.uniform(-5, 5, 5)  # random float array
print("Original:", a)

# 1. Using np.trunc()
print("trunc:", np.trunc(a))

# 2. Using astype(int)
print("astype:", a.astype(int))

# 3. Using np.floor()
print("floor:", np.floor(a))

# 4. Using np.ceil()
print("ceil:", np.ceil(a))

# 5. Using modulus (%)
print("modulus:", a - a % 1)

Original: [-4.67468231 -1.45078791  0.64502918 -4.04703972 -0.79714425]
trunc: [-4. -1.  0. -4. -0.]
astype: [-4 -1  0 -4  0]
floor: [-5. -2.  0. -5. -1.]
ceil: [-4. -1.  1. -4. -0.]
modulus: [-5. -2.  0. -5. -1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(**hint**: np.arange)

In [ ]:
a = np.arange(5).reshape(1,5) * np.ones((5,1), dtype=int)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(**hint**: np.fromiter)

In [ ]:
def gen():
    for i in range(10):
        yield i

a = np.fromiter(gen(), dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(**hint**: np.linspace)

In [ ]:
a = np.linspace(0,10,6)
print(a)

[ 0.  2.  4.  6.  8. 10.]


#### 40. Create a random vector of size 10 and sort it (★★☆)
(**hint**: sort)

In [ ]:
a = np.random.random(10)
a.sort()
print(a)

[0.22480509 0.24098832 0.3101276  0.40033798 0.53311507 0.62114659
 0.76672908 0.78113094 0.88021967 0.93202346]
